### ISSUE TITLE
copy_engine: Pinned buffer allocation failed

### ISSUE THREAD

**Issue by wespiard** [OFS/examples-afu#3]
I am getting a `Pinned buffer allocation failed!` error when trying to run the [copy_engine](../blob/ofs-2023.1-1/tutorial/afu_types/01_pim_ifc/hello_world) example on a d5005 PAC.

The d5005 PAC's FIM is of the recent `2023.1` release:
```bash
❯ fpgainfo fme
Intel FPGA Programmable Acceleration Card D5005
Board Management Controller, MAX10 NIOS FW version: 2.0.13
Board Management Controller, MAX10 Build version: 2.0.8
//****** FME ******//
Object Id                        : 0xF000000
PCIe s:b:d.f                     : 0000:04:00.0
Vendor Id                        : 0x8086
Device Id                        : 0xBCCE
SubVendor Id                     : 0x8086
SubDevice Id                     : 0x138D
Socket Id                        : 0x00
Ports Num                        : 01
Bitstream Id                     : 0x4010002AF4DE3BD
Bitstream Version                : 4.0.1
Pr Interface Id                  : 2b5c1c35-9ec4-54ec-8835-94ce6b6c3461
Boot Page                        : user
```

Additionally, I'm using the `ofs-2023.1-1` tag of this `examples-afu` repo, and the `pr_build_template` provided in [this 2023.1 release](https://github.com/OFS/ofs-d5005/releases/tag/ofs-2023.1-1).

The compilation finished and I was able to load the bitstream with `fpgasupdate`. I am able to simulate the `copy_engine` design with ASE to completion.

Here is the full output:
```bash
❯ ./copy_engine
AFU properties:
  Clock MHz: 250
  Data bus number of bytes: 64
  Number of interrupt IDs available: 4
  Maximum burst length: 256
  Maximum allowed requests in flight: 1024

Test parameters:
  Chunk size (bytes per read or write request): 8192
  Completion frequency (commands between completions): 32
  Use interrupts: No
  Maximum requests in flight: 1024

Pinned buffer allocation failed!
```

The `hello_world` example simulates and runs on the PAC without error.

I'm posting the issue here because I'm not sure if it's an issue specifically with the d5005 or not.

**Comment by wespiard** [comment]
I believe so.

```bash
❯ cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt2)/boot/vmlinuz-6.1.22-dfl root=UUID=ecceb1ce-776e-48ae-970b-3e42ed2eab75 ro crashkernel=auto intel_iommu=on pcie=realloc hugepagesz=2M hugepages=200 rd.auto=1
```

I followed the instructions [here](https://ofs.github.io/hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005/#12-terminology:~:text=etc/default/grub-,7,-.%20In%20the) (modifying the GRUB_CMDLINE_LINUX variable in `/etc/default/grub`.

**Comment by chipb-intel** [comment]
Are you running as an unprivileged user? I suspect you may be running into the `memlock` limit for your user. Try verifying the output from `ulimit -a`. Does [this section of the OPAE installation guide](https://ofs.github.io/sw/install_guide/installation_guide/#memlock-limit) help you advance any further?

**Comment by wespiard** [comment]
> Are you running as an unprivileged user? I suspect you may be running into the `memlock` limit for your user. Try verifying the output from `ulimit -a`. Does [this section of the OPAE installation guide](https://ofs.github.io/sw/install_guide/installation_guide/#memlock-limit) help you advance any further?

Looks like this was the issue. Ran the `copy_engine` executable with `sudo` and it worked. 

I'll look into whether or not I should remove the limit for regular users once anyone besides myself is accessing the PAC. 

Thank you!
